### PR TITLE
Scales canvas when displaying on a Retina Display

### PR DESCRIPTION
**Pull request by qubist**
Can you @Connoropolous test that this still works on your (I'm inferring from previous conversations) non-Retina display?

### CODE REVIEW

**Comment by Connoropolous** [comment]
@qubist not sure... I have a Retina Display and a 4K monitor so we'll see

**Comment by qubist** [comment]
Ooh interesting, do you notice a difference? On my monitor, this change makes things look much sharper and doesn't mess up any scaling. The canvas version and your html version of the goal card are indistinguishable, where before the canvas version looked blurry and your version looked crisp.

**Comment by Connoropolous** [comment]
Looks ammmmazing though... Let's merge this, and fix it for non-retinas if we find out that it's not working.

**Comment by qubist** [comment]
Great!

**Pull request merged**
